version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: thender_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c shared_buffers=32MB -c max_connections=20
    deploy:
      resources:
        limits:
          cpus: '0.30'      
          memory: 256M      

  web:
    build: .
    container_name: thender_web
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - '.env'
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.40'     
          memory: 256M      

volumes:
  postgres_data: